### ISSUE TITLE
error on import

### ISSUE THREAD

**Issue by kodeine** [ng2-ui/ng2-auto-complete#11]
Hello,
i am getting this error when i try to import the module.

code:
```
import {AutoCompleteDirective} from "ng2-auto-complete";
@Component({
    templateUrl: ....
    directives: [REACTIVE_FORM_DIRECTIVES, AutoCompleteDirective],
....
})
```

error
```
/project/node_modules/ng2-auto-complete/dist/auto-complete.directive.ts:1
import {
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

**Comment by kodeine** [comment]
Plunker Example: http://embed.plnkr.co/32syXF/ stopped working ?

**Comment by allenhwkim** [comment]
UPgraded to RC5. plnkr is still with RC4. 
Wither I filx it with RC4 or upgrade to RC5.

**Comment by allenhwkim** [comment]
Plunker is temporarily fixed to 0.4.2. 
  map['auto-complete'] = 'https://npmcdn.com/ng2-auto-complete@0.4.2';

**Comment by kodeine** [comment]
Btw, any idea why i get the error i mentioned in my first post?

**Comment by allenhwkim** [comment]
@kodeine, no idea. It's syntax parsing error.

ParseError: 'import' and 'export' may appear only with 'sourceType: module'

If you have a plnkr, it would be helpful.

**Comment by kodeine** [comment]
@allenhwkim well i installed the package and called the import and i get that error.

**Comment by allenhwkim** [comment]
@kodeine I will create a RC5 plnkr, and you may show me your issue based on that.

**Comment by kodeine** [comment]
@allenhwkim thanks

**Comment by kodeine** [comment]
@allenhwkim i am on Rc4 right now btw, i wonder why right after import i get the error.

```
import {AutoCompleteDirective, AutoCompleteComponent} from "ng2-auto-complete";
@Component({
    templateUrl: 'build/pages/request/new/new.request.html',
    directives: [REACTIVE_FORM_DIRECTIVES, AutoCompleteDirective, AutoCompleteComponent],
})

export class NewPage {
    public searchStr;
    public googleGeoCode: string = "https://maps.googleapis.com/maps/api/geocode/json?address=:keyword";
....
```

template
```html
            <input auto-complete [(ngModel)]="searchStr" [source]="googleGeoCode"
            [ngModelOptions]="{standalone: true}"
            display-property-name="formatted_address"
            path-to-data="results"></input>
            {{ searchStr | json }}
```

**Comment by allenhwkim** [comment]
RC5 plnkr  https://plnkr.co/edit/1N4onb

**Comment by allenhwkim** [comment]
if you are on RC4, please use version 0.4.2

**Comment by kodeine** [comment]
@allenhwkim i'm actually using [IonicFramework](http://github.com/driftyco/ionic), so they are on rc4. 
same error, 
```
/home/abc/project/node_modules/ng2-auto-complete/dist/auto-complete.ts:1
import {Injectable} from "@angular/core";
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
```

package.json: `    "ng2-auto-complete": "^0.4.2",`

**Comment by allenhwkim** [comment]
I don't understand why it's accessing `.ts` file instead of `.js` file.  if main is `index.js` and defaultExtension is `js`. There is no reason to access `.ts` file.

**Comment by allenhwkim** [comment]
This may help? https://github.com/urish/angular2-moment/issues/28

**Comment by kodeine** [comment]
@allenhwkim thanks, i tried that but now its a different error.

```
browser_adapter.js:84 ORIGINAL EXCEPTION: No Directive annotation found on AutoCompleteDirectiveBrowserDomAdapter.logError @ browser_adapter.js:84ExceptionHandler.call @ exception_handler.js:74(anonymous function) @ application_ref.js:337schedulerFn @ async.js:139SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:127onError @ ng_zone.js:124onHandleError @ ng_zone_impl.js:74ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:86NgZone.runGuarded @ ng_zone.js:240outsideHandler @ dom_events.js:27ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
browser_adapter.js:84 ORIGINAL STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:84ExceptionHandler.call @ exception_handler.js:77(anonymous function) @ application_ref.js:337schedulerFn @ async.js:139SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:127onError @ ng_zone.js:124onHandleError @ ng_zone_impl.js:74ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:86NgZone.runGuarded @ ng_zone.js:240outsideHandler @ dom_events.js:27ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
browser_adapter.js:84 Error: No Directive annotation found on AutoCompleteDirective
    at new BaseException (http://localhost:8100/build/js/app.bundle.js:6390:23)
    at DirectiveResolver.resolve (http://localhost:8100/build/js/app.bundle.js:13677:15)
    at CompileMetadataResolver.getDirectiveMetadata (http://localhost:8100/build/js/app.bundle.js:18583:51)
    at http://localhost:8100/build/js/app.bundle.js:18705:62
    at Array.map (native)
    at CompileMetadataResolver.getViewDirectivesMetadata (http://localhost:8100/build/js/app.bundle.js:18705:27)
    at RuntimeCompiler._getCompiledTemplate (http://localhost:8100/build/js/app.bundle.js:22692:36)
    at RuntimeCompiler._getTransitiveCompiledTemplates (http://localhost:8100/build/js/app.bundle.js:22710:80)
    at http://localhost:8100/build/js/app.bundle.js:22713:77
    at Array.forEach (native)BrowserDomAdapter.logError @ browser_adapter.js:84ExceptionHandler.call @ exception_handler.js:78(anonymous function) @ application_ref.js:337schedulerFn @ async.js:139SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:127onError @ ng_zone.js:124onHandleError @ ng_zone_impl.js:74ZoneDelegate.handleError @ zone.js:327Zone.runGuarded @ zone.js:233NgZoneImpl.runInnerGuarded @ ng_zone_impl.js:86NgZone.runGuarded @ ng_zone.js:240outsideHandler @ dom_events.js:27ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256ZoneTask.invoke @ zone.js:423
browser_adapter.js:84 ERROR CONTEXT:
```

**Comment by allenhwkim** [comment]
I have released .umd.js version, so that it does not use typescript anymore. It may help.

**Comment by allenhwkim** [comment]
Closing this for inactivity. Please create another issue if not resolved with the recent release.
