### ISSUE TITLE
error if i dont use input element

### ISSUE THREAD

**Issue by kodeine** [ng2-ui/ng2-auto-complete#14]
Hello,
Since i'm using angular2 material, it doesnt use regular input field so i have to use <md-input ...>
but as soon i click on the input i see the following error.

```html
            <md-input auto-complete
                    [(ngModel)]="myData"
                    placeholder="Enter Address(min. 2 chars)"
                    [source]="googleGeoCode"
                    display-property-name="formatted_address"
                    path-to-data="results"
                    [ngModelOptions]="{standalone: true}"
                    min-chars="2"></md-input> {{model4 | json}}<br/><br/>
```

```ts
EXCEPTION: TypeError: Cannot read property 'instance' of undefinedBrowserDomAdapter.logError @ browser_adapter.js:85BrowserDomAdapter.logGroup @ browser_adapter.js:95ExceptionHandler.call @ exception_handler.js:66next @ application_ref.js:348schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:77onError @ ng_zone.js:124onHandleError @ ng_zone_impl.js:75ZoneDelegate.handleError @ zone.js:336Zone.runTask @ zone.js:268ZoneTask.invoke @ zone.js:433
browser_adapter.js:85 STACKTRACE:BrowserDomAdapter.logError @ browser_adapter.js:85ExceptionHandler.call @ exception_handler.js:68next @ application_ref.js:348schedulerFn @ async.js:89SafeSubscriber.__tryOrUnsub @ Subscriber.js:225SafeSubscriber.next @ Subscriber.js:174Subscriber._next @ Subscriber.js:124Subscriber.next @ Subscriber.js:88Subject._finalNext @ Subject.js:128Subject._next @ Subject.js:120Subject.next @ Subject.js:77EventEmitter.emit @ async.js:77onError @ ng_zone.js:124onHandleError @ ng_zone_impl.js:75ZoneDelegate.handleError @ zone.js:336Zone.runTask @ zone.js:268ZoneTask.invoke @ zone.js:433
browser_adapter.js:85 TypeError: Cannot read property 'instance' of undefined
    at AutoCompleteDirective.styleAutoCompleteDropdown (http://localhost:3000/main.bundle.js:1816:47)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:16485:38)
    at Object.onInvokeTask (http://localhost:3000/vendor.bundle.js:47232:41)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:16484:43)
    at Zone.runTask (http://localhost:3000/polyfills.bundle.js:16385:48)
    at ZoneTask.invoke (http://localhost:3000/polyfills.bundle.js:16553:34)
  -------------   Elapsed: 19 ms; At: Thu Sep 01 2016 01:03:40 GMT-0500 (CDT)   -------------  
    at Object.onScheduleTask (http://localhost:3000/polyfills.bundle.js:16058:23)
    at ZoneDelegate.scheduleTask (http://localhost:3000/polyfills.bundle.js:16462:50)
    at Zone.scheduleMacroTask (http://localhost:3000/polyfills.bundle.js:16402:40)
    at http://localhost:3000/polyfills.bundle.js:17461:30
    at setTimeout (eval at createNamedFn (http://localhost:3000/polyfills.bundle.js:1:0), <anonymous>:3:37)
    at AutoCompleteDirective.showAutoCompleteDropdown (http://localhost:3000/main.bundle.js:1875:9)
    at DebugAppView._View_Signup2._handle_click_11_1 (Signup.ngfactory.js:1998:49)
    at http://localhost:3000/vendor.bundle.js:65392:24
    at http://localhost:3000/vendor.bundle.js:21964:36
    at http://localhost:3000/vendor.bundle.js:33352:111
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:16452:29)
    at Object.onInvoke (http://localhost:3000/vendor.bundle.js:47241:41)
    at ZoneDelegate.invoke (http://localhost:3000/polyfills.bundle.js:16451:35)
    at Zone.runGuarded (http://localhost:3000/polyfills.bundle.js:16359:48)
    at NgZoneImpl.runInnerGuarded (http://localhost:3000/vendor.bundle.js:47274:78)
    at NgZone.runGuarded (http://localhost:3000/vendor.bundle.js:31929:73)
    at HTMLElement.outsideHandler (http://localhost:3000/vendor.bundle.js:33352:79)
    at ZoneDelegate.invokeTask (http://localhost:3000/polyfills.bundle.js:16485:38)
    at Zone.runTask (http://localhost:3000/polyfills.bundle.js:16385:48)
    at HTMLElement.ZoneTask.invoke (http://localhost:3000/polyfills.bundle.js:16553:34)
```

**Comment by allenhwkim** [comment]
Are you using RC5?
If so, please create a plunker, so that I can debug it.

**Comment by kodeine** [comment]
@allenhwkim hello,
i couldnt make the plunker but i've pushed the [project on github](https://github.com/kodeine/ng2-test/invitations). 

can you please take a look at `src/app/signup/`

```
# install the repo with npm
npm install

# start the server
npm start

# use Hot Module Replacement
npm run server:dev:hmr
```

**Comment by kodeine** [comment]
@allenhwkim 
the error is at 
```
styleAutoCompleteDropdown= () => {
    let component = this.componentRef.instance;
```
when i use `<md-input auto-complete`,  `this.componentRef.instance` is `undefined`

**Comment by allenhwkim** [comment]
Thanks I will take a look at it when I get home

**Comment by allenhwkim** [comment]
Just curious, could you add some reference of having benefit of using `formControlName`?

**Comment by kodeine** [comment]
Ill try that in a bit, just got out of office...

**Comment by kodeine** [comment]
@allenhwkim just added 
```
 <md-input ng2-auto-complete
                   formControlName="myData"
```
but same issue, `Cannot read property 'instance' `

**Comment by kodeine** [comment]
@allenhwkim any luck? sorry to bother you again with this.

**Comment by allenhwkim** [comment]
There is some racing condition between `hideAutoCompleteDropdown` and `showAutoCompleteDropdown`

This does not happen without material design. My guess is there is some animation going on and it makes hiding autocomplete dropdown happens not immediately, but asynchronously

If you change the code to have setTimeout after hiding it, it seems working.
Could you try this, and make PR if works fine?

```
  showAutoCompleteDropdown() {
    document.addEventListener('click', this.hideAutoCompleteDropdown);
    this.hideAutoCompleteDropdown();
    setTimeout(() => {

      let factory = this.resolver.resolveComponentFactory(AutoCompleteComponent);

      this.componentRef = this.viewContainerRef.createComponent(factory);
      this.acEl = this.componentRef.location.nativeElement;
      let component = this.componentRef.instance;

  console.log('xxxxxxxxxxxxxxxxxxxxx', this.componentRef);

      component.listFormatter = this.listFormatter;
      //component.prefillFunc = this.prefillFunc;
      component.pathToData = this.pathToData;
      component.minChars = this.minChars;
      component.valuePropertyName = this.valuePropertyName || 'id';
      component.displayPropertyName = this.displayPropertyName || 'value';
      component.source = this.source;
      component.placeholder = this.placeholder;
      component.valueSelected.subscribe(this.selectNewValue);

      this.acEl.style.display = 'none';
      setTimeout(this.styleAutoCompleteDropdown);
    });
  }
```

**Comment by kodeine** [comment]
okay that helps a little initially, so it has the material style initially, but when i click on it, i see the <input field which i assume is being called from the component itself. so on click old input + new md-input are visible. 

secondly the css does not seem to work from the page. im trying to give it full width and it doesnt just effect.

**Comment by kodeine** [comment]
@allenhwkim i dont understand why another input comes on top of the orignal input field defined in template. Is there a way to just get the values from orignal instead of placing a new dropdown input on top of it? that will help totally avoid the input css as well.

**Comment by allenhwkim** [comment]
@kodeine this is by design. 

The value you enter for `autocomplete` should be different from the value that actually that you have. 

e.g. Your original value `abc` should not be changed when you autocomplete it with `a` then type ESC to cancel your action.

**Comment by allenhwkim** [comment]
Looked into how material design works.

md-input has its own input within it.

This `ng2-auto-complete` is designed to be located immediately after `input` tag. However because of `md-input` is only exposed, it's not possible to add this directive right after `input` tag.

![image](https://cloud.githubusercontent.com/assets/1437734/18257961/99db0d28-739a-11e6-92ec-c1052105939c.png)

I will look into some solution to resolve this, but it needs some time.

styling is not an issue for this. It's conflict between two designs; `md-input` and `ng2-auto-complete`.

**Comment by allenhwkim** [comment]
To solve this, I have to move `auto-complete` tag right after `input` tag, not `md-input`, but I am not sure it's possible or not at this moment. Needs some trials for it.

**Comment by kodeine** [comment]
@allenhwkim thanks a lot for trying and debugging this. i hope we can find some solution.

**Comment by allenhwkim** [comment]
Made change for material design.

**Comment by allenhwkim** [comment]
Closing this for inactivity. Please create another issue if not resolved with the recent release.
